#!/usr/bin/env bash

# alias part
## 返回桌面
if [ -d ~/Desktop ]; then
    alias ddd='cd ~/Desktop'
fi

## ls
alias ll='ls -al'

## trans
alias transe='trans -no-ansi en:zh-CN'
alias transc='trans -no-ansi zh-CN:en'
